### ISSUE TITLE
Error survey.analytics  v 1.1.9

### ISSUE THREAD

**Issue by aelhadi** [surveyjs/survey-analytics#10]
ngAfterViewInit(): void {
..
..
..
..
..
    const visPanel = new SurveyAnalytics.VisualizationPanel(
     document.getElementById('surveyAnalyticsContainer'),
     this.survey.getAllQuestions(),
     this.normalizedData
   );
    visPanel.render();
..
..
..
..
..

uncaught TypeError: Cannot read property 'document' of undefined
    at survey.analytics.js:25623
    at Object.163 (survey.analytics.js:35169)
    at o (survey.analytics.js:756)
    at survey.analytics.js:756
    at Object.719.../constants/numerical (survey.analytics.js:107754)
    at o (survey.analytics.js:756)
    at survey.analytics.js:756
    at Object.1.../src/lib (survey.analytics.js:759)
    at o (survey.analytics.js:756)
    at survey.analytics.js:756

**Comment by tsv2013** [comment]
Thank you for the project you've provided. This issue is related to plotly.js library and discussed in this thread - https://github.com/plotly/angular-plotly.js/issues/75

As recommended, i've changes tsconfig file target option to the following:
```JSON
      "target": "es5",
```

and it works for me now
