### ISSUE TITLE
Survey table pagination

### ISSUE THREAD

**Issue by prathap-ravi** [surveyjs/survey-analytics#108]
Hello, 

how do it change the number of results shown in a page? for ex: by default is shows 5, i wanted to show 10 or 15.
https://surveyjs.io/Examples/Analytics?id=nps-tabulator&platform=jQuery&theme=modern

Thanks,
Prathap

**Comment by dk981234** [comment]
Hello, 
You can set page size via the table's state. Here is an [sample](https://plnkr.co/edit/Vddds4Moa06oFJXP).

Thanks,
Dmitry
SurveyJS Team

**Comment by prathap-ravi** [comment]
Thank you 👍  @dk981234
