### ISSUE TITLE
Question about rendering the Analytics

### ISSUE THREAD

**Issue by nathan-at-jisc** [surveyjs/survey-analytics#110]
Hi,

Just a quick note before my question. I'm a team lead at Jisc, working on a replacement service called [onlinesurveys](https://onlinesurveys.ac.uk) and we're using some of SurveyJS in our product. We're currently in the process of buying our developer licenses as we really like the product. We have around 100,000 users who use our system, and our surveys can have upwards of 50k responses, so as you can imagine, analytics can get complicated.

How would you recommend we get past this using SurveyJS? Should we just render the analytics on our API and send back the HTML etc?

For reference, we're using Serverless (Node.js) for the API and Serverless Components (Web - React) for the UI.

For small surveys, it's fine for us to render these analytics on the page.

Just to reiterate, at Jisc we're really happy with the product/service you are providing. SurveyJS is fantastic and hopefully, over the course of this project we will have the opportunity to contribute as we have a few ideas!

**Comment by nathan-at-jisc** [comment]
Also, when I try rendering certain surveys, I get the following error:

```

**Comment by tsv2013** [comment]
Thank you for for the interest in our product and for your kind words.

SurveyJS products are the client side JavaScript libraries.
And unfortunately at this moment we don't provide any server-side code to work with survey results.
Now all survey results should be fetched onto client side and then processed via survey-analytics locally.
Processing of large data arrays can be rather time-consuming on the client side.
We're aware of this problem and thinking how we could solve it.

The ideal solution for me seems to pre-populate statistics during the post survey results operation.
In this case we could return to the client side ready pre-counted data and just show them.
But at this moment these are the thoughts only. And we haven't any plans to implement it in the near future.

**Comment by tsv2013** [comment]
As for the error you get, could you provide us with a plunker or other live sample illustrating the issue?

**Comment by nathan-at-jisc** [comment]
Thanks for your quick response. I like your solution regarding server-side rendered results. I was thinking of a fork where we do something similar, and render a statistics object that's just passed in, as opposed to raw data. We're going to think about this on our time. And yes, of course, I'll get that done shortly.

**Comment by nathan-at-jisc** [comment]
It seemed to me that during the testing. When there were only a few results, the analytics was fine but seemed to 'crash' (display the error listed above) when there were more results. I will try to replicate again shortly.

However, for different questions, it could handle 40k+ responses no problem, so the error may be on my side with that specific survey. It seemed that when rendering only on visualisation (text), and nothing else, it crashed with lots of responses. As if from an error with the wordcloud.

**Comment by tsv2013** [comment]
You can unregister the "WordCloud" visualizer:
```JS
VisualizationManager.unregisterVisualizerForAll(WordCloud);
```
It's indeed the most problematic one.
