### ISSUE TITLE
HOW to set size of charts 

### ISSUE THREAD

**Issue by rajeshsingh1977** [surveyjs/survey-analytics#120]
i don't see any option to set size of the chart of survey analytics e.g. pie chart comes in 200 X 200 px

**Comment by tsv2013** [comment]
Hello,
You can subscribe the `SurveyAnalytics.PlotlySetup.onPlotCreating` static event:

```JS
SurveyAnalytics.PlotlySetup.onPlotCreating.add(function(visualizer, options) {
  // options.traces - you can change traces according your needs
  // options.layout
  // options.config
});
```

Thanks, Serge  
SurveyJS Team
