### ISSUE TITLE
Regarding responsive charts

### ISSUE THREAD

**Issue by jinhojang6** [surveyjs/survey-analytics#125]
Hi, I'm looking over this library and if everything is good, I will purchase a license soon.

But I've found a couple of issues regarding responsiveness, as my project is targeting mobile users mostly.

1. I found that the Y-axis(questions) is cut off for long sentence (e.g., develop apps for ..) as below. Can I show full text?
<img width="609" alt="Screen Shot 2021-02-24 at 8 45 02 PM" src="https://user-images.githubusercontent.com/41753422/108996230-7950f500-76e1-11eb-8f1c-4acd4fdb7d83.png">

2. The rating chart is cut off on small screens as below. Is it possible to make it responsive?
<img width="429" alt="Screen Shot 2021-02-24 at 8 48 25 PM" src="https://user-images.githubusercontent.com/41753422/108996496-ccc34300-76e1-11eb-8b59-e5fb767ab65a.png">

3. Does this library offer localization?

**Comment by tsv2013** [comment]
1. You can set the `labelTruncateLength` to -1 to disable truncating (https://github.com/surveyjs/survey-analytics/issues/98)
2. You can use the `SurveyAnalytics.PlotlySetup.onPlotCreating` event as described [here](https://github.com/surveyjs/survey-analytics/issues/120) and [here](https://github.com/surveyjs/survey-analytics/issues/101)
3. Yes, here is the live sample - https://surveyjs.io/Examples/Analytics?id=multilanguage&platform=jQuery&theme=modern

**Comment by jinhojang6** [comment]
@tsv2013 

1. It doesn't truncate the text with the -1 option, but the text itself cannot be wrapped. It's clipped as below. Do you know how to solve it? CSS doesn't work here
<img width="364" alt="Screen Shot 2021-03-01 at 1 46 04 AM" src="https://user-images.githubusercontent.com/41753422/109426256-fd7fe100-7a2f-11eb-8699-e4be320c4e98.png">

2. I found the `responsive` option from Plotly (https://plotly.com/javascript/responsive-fluid-layout/) but it doesn't work with SurveyJS. Do you know if it works? Here is my code: 

```
    SurveyAnalytics
    .PlotlySetup
    .onPlotCreating
    .add((model, options) => {
        if (model.chartType !== "gauge") 
            return;
        options.config = { ...options.config, responsive: true };
        console.log(options)
    });
```
