### ISSUE TITLE
emailid does not turn up in word cloud

### ISSUE THREAD

**Issue by prashanthsridhar** [surveyjs/survey-analytics#126]
it works in text table form
![image](https://user-images.githubusercontent.com/11289456/109820207-ce00ec80-7c5a-11eb-88a1-168bba9185f6.png)

---------------------------------------------------------------------------------------------------
it doesnt show up in word cloud
![image](https://user-images.githubusercontent.com/11289456/109820324-e6710700-7c5a-11eb-978c-1d0e4da244f2.png)

**Comment by tsv2013** [comment]
I'll check it and update this thread.

**Comment by prashanthsridhar** [comment]
@tsv2013 as a temporary fix, is there a way to disable wordcloud and keep just the text table?

**Comment by tsv2013** [comment]
I've created a live sample of the email visualization. Here it is - https://plnkr.co/edit/jvzxdHQxV7ij5D5g . It works ok for me.

You can unregister the wordcloud visualizer as suggested in this thread - https://surveyjs.answerdesk.io/ticket/details/t5330/analytics-angular-hide-wordcloud-option-from-other-items-and-comments:
```JS
SurveyAnalytics.VisualizationManager.unregisterVisualizerForAll(SurveyAnalytics.WordCloud);
```

**Comment by prashanthsridhar** [comment]
@tsv2013 thank you for a quick response. I Just wanted to clarify something,
Q1) for the same input there are different word clouds. I've used your example  and just by clicking on refresh there are multiple versions of the word cloud.
![image](https://user-images.githubusercontent.com/11289456/110088960-8e9de180-7dbb-11eb-8ee8-cade852231fe.png)
after 3 refresh
![image](https://user-images.githubusercontent.com/11289456/110089042-a2e1de80-7dbb-11eb-920c-fbd816e4c7e0.png)



Q2) If the input is the same ,there is no word cloud,ideally it should be there right?
![image](https://user-images.githubusercontent.com/11289456/110091370-61066780-7dbe-11eb-8342-23c4fafcc2ce.png)

**Comment by tsv2013** [comment]
Q1: this is how wordcloud library works, it's not related to SurveyJS code AFAIU
Q2: haven't got you

**Comment by prashanthsridhar** [comment]
Thank you .
Regarding Q2.

if we give the same input in four surveys,there is no wordcloud.
the image below has one input and there is an output wordcloud.
![image](https://user-images.githubusercontent.com/11289456/110102571-f4de3080-7dca-11eb-8c83-41525927432b.png)

the image below has four of the same entries and on the right is nothing.
![image](https://user-images.githubusercontent.com/11289456/110102887-4f778c80-7dcb-11eb-8933-0937e87ce51d.png)

**Comment by tsv2013** [comment]
You have too few data.

And the result font size is too small.
You can set the 
```JS
SurveyAnalytics.WordCloudAdapter.weightFactor = 5;
```

As shown in this sample - https://plnkr.co/edit/CACEJF0mjdJeMr21

**Comment by prashanthsridhar** [comment]
Thank You @tsv2013 , i just lost track of this one ,apologies for not closing. The fix helped :)
