### ISSUE TITLE
Matrix multiple choice does not seem to have visualisation

### ISSUE THREAD

**Issue by prashanthsridhar** [surveyjs/survey-analytics#127]
I tried creating a survey with matrix multiple choice. it was seen in the survey but there was no graphic available for the same

**Comment by prashanthsridhar** [comment]
Is there a graphic available for matrix multiple choice question?

**Comment by tsv2013** [comment]
Here is the plunker sample - https://plnkr.co/edit/bBBqwpUy9uCrM6pu

shows matrix + matrixdropdown

**Comment by prashanthsridhar** [comment]
@tsv2013 ,if we have a survey creator license,do we need a separate survey analytics license?

**Comment by tsv2013** [comment]
@prashanthsridhar yes, you do need a separate license

**Comment by prashanthsridhar** [comment]
@tsv2013 HI, we got the license but im not able to find any documentation on how to integrate it. Can you please share some literature on that.

**Comment by tsv2013** [comment]
Right now we have the following examples https://surveyjs.io/Examples/Analytics and documentation articles https://surveyjs.io/Documentation/Analytics on our site. I've also shared a working sample for you - https://plnkr.co/edit/bBBqwpUy9uCrM6pu . Does it work for you? If no, could you modify this live sample to illustrate your issue?

**Comment by prashanthsridhar** [comment]
Hi @tsv2013 ,
in you example [here](https://plnkr.co/edit/bBBqwpUy9uCrM6pu), the json in like

> {
          type: "matrixdropdown",
          name: "question2",
          title: "What do you feel about these brands?",
          isRequired: true,
          columns: [
            {
              name: "Column 1",
              title: "My Opinion",
              choices: ["High Quality", "Natural", "Trustworthy"],
            },
            {
              name: "Column 2",
              title: "Review Mark",
              choices: [1, 2, 3, 4, 5],
            },
          ],
          rows: ["Lizol", "Harpic"],
        },

the **choices** are in inside each individual entry in columns array.

But in the sample code for surveyCreator, i just added a matrixmultiple choice question and the json is like

>  "elements": [
    {
     "type": "matrixdropdown",
     "name": "question1",
     "columns": [
      {
       "name": "Column 1"
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      "Row 1",
      "Row 2"
     ]
The **choices** have a separate array, in this scenario the graphics are not populated,please try and let me know [plunker code](https://plnkr.co/edit/MVGEaiDI8saFFm2a)

**Comment by prashanthsridhar** [comment]
[Here ](https://plnkr.co/edit/SJhDfCZmIH6ATHXT)is an example with a fully populated sample survey,please have a look at question1

**Comment by tsv2013** [comment]
@prashanthsridhar Thanks, I'll take a look

**Comment by tsv2013** [comment]
I've reproduces the issue. It's a bug indeed.

**Comment by tsv2013** [comment]
I've fixed the issue, fix will be available in the nearest minor update, see the milestone.
