### ISSUE TITLE
How to display comment that user wrote in his response in tabulator?

### ISSUE THREAD

**Issue by Legomegger** [surveyjs/survey-analytics#143]
Hello, how could I display comment, my question has a hasComment: true

**Comment by Legomegger** [comment]
And in general how does tabulator display columns? It matches questions json and response json?

**Comment by tsv2013** [comment]
Table columns are generated by questions. Probably comments are not implemented yet we'll check it and write back here.

**Comment by dk981234** [comment]
Hello,

We've implemented support for questions with comments.  After the column with the question that has a comment, another column with comments to the question will appear. The title of this column will match the 'commentText' value of the question.

Thanks,
Dmitry
SurveyJS Team
