### ISSUE TITLE
Matrix question type analytics

### ISSUE THREAD

**Issue by tusharsinhparmar** [surveyjs/survey-analytics#15]
How to replace column text with trace 0, trace 1, and more?
![matrix_trace_screenshot](https://user-images.githubusercontent.com/38554686/69618235-8b1b9680-105f-11ea-8387-32c595eb96f0.png)

**Comment by tsv2013** [comment]
What version of survey-analytics package are you using? It should be fixed in the latest version.
Here is the live demo - https://surveyjs.io/Service/SurveyNPS

**Comment by tusharsinhparmar** [comment]
Thanks for reply but i m talking about matrix type question there are rows and columns i m fine with row that are Com and Dev but in column graph display value with trace it should be column value or text not trace.

**Comment by tsv2013** [comment]
Can you share a minimal sample illustrating the issue?

**Comment by tusharsinhparmar** [comment]
Sure,

I temporary update survey.analytics.js file using below code.
line no: 453
And its working fine but let me know its right or not

-----------code------------
`datasets.forEach(function (dataset,i) {
                        if (_this.chartType === "pie") {
                            traces.push(Object.assign({}, traceConfig, {
                                values: dataset,
                                labels: labels
                            }));
                        }
                        else {
                            var nm="";
                            if(question.columns[i]  != undefined && question.columns[i]  != null )
                            {
                                nm  =question.columns[i].calculatedText;
                            }
                            traces.push(Object.assign({}, traceConfig, { x: dataset },{name:nm}));
                        }
                    });`
----------Endcode-------------

**Comment by tusharsinhparmar** [comment]
I'm using version 1.1.21

**Comment by tsv2013** [comment]
Can you share a sample survey JSON?

**Comment by tusharsinhparmar** [comment]
Question: 
`{"pages":[{"name":"page1","elements":[{"type":"matrix","name":"question1","columns":["Column 1","Column 2","Column 3"],"rows":["Row 1","Row 2"]}]}]}`

Answer:
`{"question1":{"Row 1":"Column 1","Row 2":"Column 2"}}`

**Comment by tsv2013** [comment]
I've fixed the issue via the related commit. Fix will be available in the nearest update.
