### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by tortuetorche** [surveyjs/survey-analytics#17]
Hi folks,

Is Survery Analytics, like the Survey Creator, NOT FREE for commercial using?
But free for non-commercial use (via the [Creative Commons (CC) Attribution-NonCommercial licence](https://creativecommons.org/licenses/by-nc/3.0/))?

Have a good day,
Tortue Torche

**Comment by tsv2013** [comment]
Yes, survey-analytics is NOT FREE product for commercial using.

**Comment by kelvin-homann** [comment]
Is it already possible to purchase a License or will that be once its out of beta?
Or is it included with the Creator License?

**Comment by andrewtelnov** [comment]
@tortuetorche @kelvin-homann Sorry for the late answer.
Currently Survey Analytics in Beta. We need more users and more user cases to make the initial release.
I would love if you try it and provide your feedback. If your beleive that there is something missed or implemented in a wrong way, please let us know.

Thank you,
Andrew
