### ISSUE TITLE
Image Picker Default Order reversed in Graph visualization 

### ISSUE THREAD

**Issue by Adityagrao** [surveyjs/survey-analytics#171]
Steps to recreate 
- Create a survey with an Image picker question with images (1:lion, 2:giraffe, 3:panda, 4:camel) 
- Submit this survey 
- The default view is the reverse order of the images  (4,3,2,1)

Expected Result 
- Was expecting the default order to be the same order in which the options were given  - (1,2,3,4)

![image](https://user-images.githubusercontent.com/11465032/136004708-7bf7db29-5261-4fe6-a346-d51011361aff.png)
![image](https://user-images.githubusercontent.com/11465032/136004657-099d73df-378d-42d4-81b9-6be2808be658.png)

**Comment by tsv2013** [comment]
Implemented in https://github.com/surveyjs/survey-analytics/issues/242
