### ISSUE TITLE
Duplicated imports in the type declarations file

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-analytics#18]
```
import { Question } from "survey-core";
import { Question, Event } from "survey-core";
import { SurveyModel, Event } from "survey-core";
import { Question, QuestionBooleanModel } from "survey-core";
import { ItemValue } from "survey-core";
import { Question, ItemValue } from "survey-core";
```

**Comment by srivigneshwara** [comment]
Hi Team,

Is the issue fixed ? , because I can still see the same problem after updating the survey-analysis package in my application. Can  we get a duration when the bug will be resolved. 

Good Day!!
Thanks,

**Comment by tsv2013** [comment]
We're working on the fix. The typings are auto-generated and we need to find a fix/workaround for the 3rd party tool and replace this tool/create an own one.

As a workaround you can patch this type declaration file on your side.

**Comment by tsv2013** [comment]
Fix will be available in the nearest minor update, most likely tomorrow.
