### ISSUE TITLE
Question: Tabulator - how do we override default page size of 5?

### ISSUE THREAD

**Issue by prathapRC** [surveyjs/survey-analytics#189]
![image](https://user-images.githubusercontent.com/44378838/144828625-38b5b150-3a25-4aca-a288-a3fbc79a9a00.png)

**Comment by tsv2013** [comment]
You need to use the `setPageSize` function before render:
```JS
surveyAnalyticsTabulator.setPageSize(10);
```

Here is the example - https://plnkr.co/edit/Mk89AYvcBFBDBahJ
