### ISSUE TITLE
error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by smoke** [surveyjs/survey-analytics#21]
With this commit https://github.com/surveyjs/survey-analytics/commit/f53302a6a65ddd55d427ccdc5597931e82e80efb `DataTables.Settings` is used, but no such type exists.
Therefor upon building, this leads to:
`ERROR in node_modules/survey-analytics/survey.analytics.d.ts:234:33 - error TS2702: 'DataTables' only refers to a type, but is being used as a namespace here.`

**Comment by tsv2013** [comment]
Fix will be available in the nearest minor update, most likely next week.

**Comment by dave-budah** [comment]
Has this issue been fixed?.
