### ISSUE TITLE
Mark correct vs incorrect answers

### ISSUE THREAD

**Issue by olsn** [surveyjs/survey-analytics#22]
I'm current evaluating the analytics-pack for our use. I managed to mark the correct answer with an asterisk (by iterating through the questions and modifying the correct choice:

```
// if choice is correct ...
choice.locTextValue.values.default += " *";
```

My question is: Is it somehow possible to just display "correct vs. wrong answers"? Instead of all individual replies?

**Comment by tsv2013** [comment]
Do you want to mark right choices on the charts in similar way?

**Comment by olsn** [comment]
No that part I managed via `locTextValue.values.default` - we are trying to use surveyjs as a quiz-tool. And we would like to get out aggregated statistics/charts about "Question 1: 5 correct, 2 incorrect; Question 2: 7 correct, 0 incorrect; Question 3: 3 correct, 4 incorrect; etc...." (e.g. with a stacked barchart, each bar-stack is for a question, but there are many possbilities)

I know that I can take all the data a build a chart for that myself, my question was just: Does the analytics pack maybe already provide something like this? And if not - are there plans for it? :-)

**Comment by tsv2013** [comment]
Analytics pack doesn't provide this ability right now. But we'll take in account your valuable suggestion in future development.

**Comment by olsn** [comment]
Okay, it's not a "must have" currently for me, but good to know, thank you 😃 👍
