### ISSUE TITLE
Survey Tabulator allows code injection

### ISSUE THREAD

**Issue by kaestlej-tng** [surveyjs/survey-analytics#223]
Hello SurveyJS team,

the survey tabulator does not escape script tags correcltly.

I have taken the the survey tabulator example and added a HTML button with a onclick handler on it and it executes. This is a security issue and should not be the case. https://plnkr.co/edit/J99S1lklsPL6d27J

The survey editor and survey display component escape this correctly.

Best
Johannes

**Comment by tsv2013** [comment]
I've fixed the issue via the commit above. Fix will be available in 1.9.32
