### ISSUE TITLE
`Node.prototype.append` doesn't work in IE11

### ISSUE THREAD

**Issue by Hrommi** [surveyjs/survey-analytics#23]
Hi. The `append` method not support in IE. Maybe it's better to use `appendChild`?
https://github.com/surveyjs/survey-analytics/blob/cc05b13bbc5a64043c57353cae4913124e4043cb/src/tables/datatables.ts#L19
https://github.com/surveyjs/survey-analytics/blob/cc05b13bbc5a64043c57353cae4913124e4043cb/src/tables/tabulator.ts#L14

**Comment by tsv2013** [comment]
It's a bug indeed. Fix will be available in the nearest update, most likely tomorrow.

**Comment by Hrommi** [comment]
Thanks 👍
