### ISSUE TITLE
Localized Analytics example: Issues with the dropdown and code

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-analytics#237]
- [ ] The Change Locale dropdown doesn't show the selected locale.
    To reproduce the issue, change the locale using the dropdown.
    Current behavior: The dropdown displays the phrase "Change Locale" in the selected language.
    Expected behavior: The selected language persists in the dropdown.
- [ ] The example doesn't show the code that actually changes the locale.
- [ ] The phrase "Change Locale" isn't translated to French.

**Comment by tsv2013** [comment]
1. I've fixed first item

2,. 
>The example doesn't show the code that actually changes the locale.

This example actually contains this code:
```JSON
var json = {
  "locale": "fr",
  "elements": [
    {
      "type": "dropdown",
      "name": "satisfaction",
      "title": {
        "default": "How satisfied are you with the Product?",
        "ru": "Насколько Вас устраивает наш продукт?",
        "fr": "Êtes-vous satisfait du produit?"
      },
```
If survey JSON is localized then "change language" selector will be availalable. 

3. Selector now contains selected language name and doesn't contain "Change Locale" string

**Comment by tsv2013** [comment]
@RomanTsukanov you can reactivate it and we'll discuss it again to finally nail it
