### ISSUE TITLE
Implement features or hide toolbar controls that cannot be applied to Histogram

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-analytics#240]
- [x] Filtering (see also #229)
- [x] Sorting dropdown (see https://github.com/surveyjs/survey-analytics/issues/228)
- [x] "Hide empty answers" button

https://plnkr.co/edit/o7TAXNjuDh15n2Px

**Comment by tsv2013** [comment]
Hide empty answers also work - https://codepen.io/tsv2013/pen/mdgLjjQ
