### ISSUE TITLE
Bar chart may leave out series points in some cases

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-analytics#245]
In [this example](https://surveyjs.io/Examples/Analytics?id=nps-direct), the question "How many software developers are in your organization?" displays only 2 bars, but if you switch to one of the other chart types, you will see that there are more answers.

Bar:
![image](https://user-images.githubusercontent.com/18551316/170203115-1f769827-c5d1-435d-ac6e-b9b1f0a8a73b.png)

Pie:
![image](https://user-images.githubusercontent.com/18551316/170203273-23590373-f314-47ae-9faf-71a6c58dd081.png)

**Comment by tsv2013** [comment]
Fixed via the https://github.com/surveyjs/survey-analytics/commit/569ff7c6f6267a33f521819d3f8863def7fe55a1 commit.

**Comment by tsv2013** [comment]
See the https://github.com/surveyjs/survey-analytics/issues/241 issue
