### ISSUE TITLE
Hide empty charts

### ISSUE THREAD

**Issue by DydjyZ** [surveyjs/survey-analytics#26]
hi, is there a solution to hide empty charts ?

![image](https://user-images.githubusercontent.com/18429327/80986167-7a522680-8e30-11ea-8b2e-b639b613d365.png)

Thank you!

**Comment by DydjyZ** [comment]
Just found a temporary workaround :

`           
els = document.getElementsByClassName('sva-question');
for (let el of els) {
    let graph = el.getElementsByClassName("sa-visualizer__content");
    if (graph && graph[0]) {
        if (graph[0].innerHTML == "This question type is not visualized yet") {
            el.parentNode.removeChild(el);
        }
    }
}
`

**Comment by tsv2013** [comment]
When you creating a visualization panel, you pass an array of questions that you want to visualize:
```JS
var visPanel = new SurveyAnalytics.VisualizationPanel(
  document.getElementById("summaryContainer"),
  survey.getAllQuestions(),
  normalizedData
);
```

In the code above all questions are being passed. In your case you can filter - what questions to visualize.

**Comment by DydjyZ** [comment]
True thank you!
