### ISSUE TITLE
Import or export declaration in an ambient module declaration cannot reference module through relative module name.

### ISSUE THREAD

**Issue by dougalg** [surveyjs/survey-analytics#267]
Typescript: v4.4.3
survey-analytics: v1.9.41

I have upgraded to the latest survey-analytics 1.9.41 and I am receiving a typescript error:

```
Import or export declaration in an ambient module declaration cannot reference module through relative module name.
```

This is in reference to all cases of scss imports declared in the `survey-analytics.d.ts` file, eg:

```
import "./choices-table.scss";
...
import Plotly from "plotly.js-dist-min";
```

Is there any guidance on how to address this issue?

Actually, I'm a little confused as to why a CSS import is even specified in the `.d.ts` files. Is this normal?

**Comment by dougalg** [comment]
I am also seeing the following error:

```
Could not find a declaration file for module 'plotly.js-dist-min'. 'ROOT_DIR/node_modules/plotly.js-dist-min/plotly.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/plotly.js-dist-min` if it exists or add a new declaration (.d.ts) file containing `declare module 'plotly.js-dist-min';`
```

**Comment by dougalg** [comment]
I have (hopefully temporarily) resolved this by setting the following in my ts config

```
"skipLibCheck": true,
```

**Comment by tsv2013** [comment]
scss imports are used by webpack to bundle css files. 

As for plotly.js-dist-min typings, it is mentioned in devDependencies:
```JSON
    "@types/plotly.js-dist-min": "^2.3.0",
```

I can move them into dependencies section, but it looks strange

**Comment by dougalg** [comment]
I understand that CSS imports are used in the final product, by why would they be included in the TS definitions files (and especially when they also render said definitions invalid)? I'd rather not have to disable type-checking of all `.d.ts` files in order to include your library.

For plotly, would it not make sense to include `@types/plotly.js-dist-min` as a `peerDependency`? It's hard to say, since it's not strictly required for all users, but if you did that it would allow you to correctly version lock the appropriate plotly type definitions to your releases for your users.

I would like this to be considered for re-opening; I could possibly help with both of these fixes.

**Comment by tsv2013** [comment]
I'm not sure about peerDependencies transitivity, but I moved typings to them. Let's see whether it fix your issue
