### ISSUE TITLE
The VisualizationPanel.refresh method doesn't reflect changes made to the survey JSON results

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-analytics#269]
I want to add another question answer to the survey results. For this, I push a new item to the survey JSON results. After that, I call the VisualizationPanel.refresh method, however, the visualization panel doesn't show a new entry.
```
const surveyResults = [{
  "satisfaction-score": 5,
  "nps-score": 10
}...];
const updateResults = ()=>{
  const newAnswer = {'satisfaction-score': 4, 'nps-score': 9};
  surveyResults.push(newAnswer);
  visPanel.refresh();
}
```
A complete example is available [here](https://plnkr.co/edit/58V8DpNQByMirRva).

Original issue: [T10459 - Refresh Survey Result](https://surveyjs.answerdesk.io/internal/ticket/details/T10459)

**Comment by tsv2013** [comment]
Yes, earlier refresh method call led to re-rendering visualizer with new data. Now pre-counted data are cached in the `dataProvider` object of a visualizer. Refresh method leads to re-rendering visualizer content for cases of changed options or language or something similar not related to data changes.

If you change visualizer data you need whether to call the https://surveyjs.io/Documentation/Analytics?id=visualizerbase#updateData method or call the `dataProvider.reset()` method that subsequently triggers `refresh` method of a  visualizer.
