### ISSUE TITLE
How to hide the unwanted tool icons on charts

### ISSUE THREAD

**Issue by ashokkumarjuly** [surveyjs/survey-analytics#27]
Hi, 
Could you please help me to remove certain icons or whole set of icons when question is displayed in chart. 
Also, i noticed in pie chart and  doughnut chart, on mouse hover the answers are displaying twice.
<img width="729" alt="barchart" src="https://user-images.githubusercontent.com/4641914/81167151-57e81680-8fb2-11ea-8a8f-4be651db0089.png">
<img width="712" alt="pieChart" src="https://user-images.githubusercontent.com/4641914/81167356-b4e3cc80-8fb2-11ea-9030-9d5192de8521.png">

**Comment by tsv2013** [comment]
I've implemented corresponding option:
``JS
SurveyAnalytics.SelectBasePlotly.displayModeBar = false;
```

It will be available in the nearest update ()

**Comment by tsv2013** [comment]
@ashokkumarjuly  As for your second remark (duplicated answers) - I've not reproduced the issue in the 1.7.4 version.

**Comment by ashokkumarjuly** [comment]
@tsv2013, Thanks for your response. 
For label duplicate issue, will update the version to 1.7.4 and let you know.

**Comment by ashokkumarjuly** [comment]
@tsv2013, thank you. Waiting for the nearest update(). :-) 
Once updated to version 1.7.4 ,the answer duplicate issue solved.
