### ISSUE TITLE
How to stop dragging and hide chart selector UI

### ISSUE THREAD

**Issue by kryptojet** [surveyjs/survey-analytics#28]
<img width="244" alt="menu" src="https://user-images.githubusercontent.com/63332056/81809993-272d5180-955d-11ea-9a0f-71cc4a043ed7.png">

Thanks

**Comment by tsv2013** [comment]
To disable dragging you need to pass the `{ allowDynamicLayout: false }` option to the panel:
```JS
var visPanel = new VisualizationPanel(
      targetNode,
      survey.getAllQuestions(),
      data,
      { allowDynamicLayout: false }
    );
```

**Comment by tsv2013** [comment]
As for chart types selector, you need to pass only one item in chart types array:
```JS
SurveyAnalytics.SelectBasePlotly.types = ["bar", "pie", "doughnut", "scatter"];
```

e.g.
```JS
SurveyAnalytics.SelectBasePlotly.types = ["pie"];
```

This will work in 1.7.7

**Comment by kryptojet** [comment]
Thanks. 1.7.7. works perfectly. And one more question.

How to hide 'hide button' or tool bar line all?

<img width="737" alt="Screen Shot 2020-05-20 at 4 11 36 PM" src="https://user-images.githubusercontent.com/63332056/82416540-2ba1bf00-9ab5-11ea-80ee-0170acc4ead3.png">
