### ISSUE TITLE
Set a custom number of visible table row count for the Tabulator view

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-analytics#285]
Temporary solution: provide a custom list for the 'Show X entries' drop-down and call tabulator's `setPageSize` function to set a custom initial number of table rows.
[Example](https://plnkr.co/edit/Yz6xj6gEdtQNoI4U).

**Comment by tsv2013** [comment]
You need to use the following code to set page selector dropdown content and the current page size:
```JS
var surveyAnalyticsTabulator = new SurveyAnalyticsTabulator.Tabulator(
  survey,
  normalizedData,
  {
    // useNamesAsTitles: true
  }
);

surveyAnalyticsTabulator.paginationSizeSelector = [2,4,6,8,100];
surveyAnalyticsTabulator.setPageSize(4);
```
