### ISSUE TITLE
How to hide 'hide button' and tool bar line all?

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-analytics#29]
Thanks. 1.7.7. works perfectly. And one more question.

How to hide 'hide button' and tool bar line all?

<img width="737" alt="Screen Shot 2020-05-20 at 4 11 36 PM" src="https://user-images.githubusercontent.com/63332056/82416540-2ba1bf00-9ab5-11ea-80ee-0170acc4ead3.png">

_Originally posted by @kryptojet in https://github.com/surveyjs/survey-analytics/issues/28#issuecomment-631285583_

**Comment by tsv2013** [comment]
@kryptojet It's another issue

**Comment by tsv2013** [comment]
@kryptojet It's in my task list. I'll implement it as soon as I'll have time.

**Comment by kryptojet** [comment]
@tsv2013 Thanks

**Comment by tsv2013** [comment]
I've implemented the `allowHideQuestions` option in order to deny user to hide/show individual questions:
```JS
var options = {
  allowHideQuestions: false
}

var visPanel = new SurveyAnalytics.VisualizationPanel(
  document.getElementById("summaryContainer"),
  survey.getAllQuestions(),
  normalizedData,
  options
);
```
