### ISSUE TITLE
Table results -  implement option of deleting multiple records at a time

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-analytics#30]
See the https://surveyjs.answerdesk.io/ticket/details/t4114/bug-in-deleting-result thread for more detials

**Comment by tsv2013** [comment]
We need to 
- make it switcheable (on/off), off - default
- put remove button after export buttons
- align checkbox with other elements in control column

**Comment by tsv2013** [comment]
Make a common place for such an extensions

**Comment by dk981234** [comment]
Added register method for tools via these commits: https://github.com/surveyjs/survey-analytics/commit/a10c91782f81a5f30b09f13f99d6c5dd30dced84, https://github.com/surveyjs/survey-analytics/commit/e6b5fb06d879078bbdc246bd934ed7d539ffc469, https://github.com/surveyjs/survey-analytics/commit/0e7dff00b813bcfaba4466a3e9dafd2a8edb57e4
Added `toolsOptions` property to change order of tools via this [commit](https://github.com/surveyjs/survey-analytics/commit/611dd163086e8a20a516394cd68f413ecc35b387)
