### ISSUE TITLE
SurveyJS Dashboard doesn't visualize Text questions which enables a specific input type: date, time, range

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#305]
Text answers can be visualized using the Wordcloud, Table.
SurveyJS Dashboard doesn't visualize Text questions which enables a specific input type: date, time, range, etc. 

![image](https://user-images.githubusercontent.com/22372972/213980110-2c670d8f-eb1b-4d2c-9439-21aeef1e497f.png)
**Suggestion: consider histograms to visualize answer for such questions.**

[Example](https://codesandbox.io/s/winter-fire-8s0b4u?file=/src/SurveyDashboardComponent.jsx:595-605).
Original issue: [T11782 - Analytics graphs not showing](https://surveyjs.answerdesk.io/internal/ticket/details/T11782).

**Comment by tsv2013** [comment]
Continuous data can be visualized via a histogram visualizer. Here is the working plunker example - https://plnkr.co/edit/O9UoUAmwNmj4bCWh

Hope it fit for now.
@JaneSjs Probably we need to create a demo on our site.
