### ISSUE TITLE
Dashboard Toolbar tooltips translation

### ISSUE THREAD

**Issue by tiagofranciscosta** [surveyjs/survey-analytics#311]
Are this Dasboard toolbar tooltips translatable? Can't seem to find its key in the translation resources file.

![image](https://user-images.githubusercontent.com/43204804/219701676-46e40f51-e66b-40d3-8ce8-9cf757dd341f.png)

**Comment by JaneSjs** [comment]
Hello @tiagofranciscosta,
SurveyJS Dashboard uses the [plotly.js](https://plotly.com/javascript/) to visualize the Bar chart. If you wish to modify the text which appears in the modebar tooltip items, do the following:
* Add `<script src="https://cdn.plot.ly/plotly-locale-YOUR-LOCALE-latest.js"></script>` to your HTML after the plotly.js. It's recommended [here](https://plotly.com/javascript/configuration-options/#change-the-default-locale). 
* Specify the [VisualizationPanel.locale](https://surveyjs.io/dashboard/documentation/visualizationpanel#locale) property to change the default visualization panel locale. 

You can find an example [here](https://surveyjs.answerdesk.io/internal/ticket/details/T10574#472e9a3b-fbae-47f8-b06e-0e86fd38d7c6).

Please feel free to reopen this thread if you have any questions or require further assistance.
