### ISSUE TITLE
[Question] Which option can we show full title and answer?

### ISSUE THREAD

**Issue by PhuHoaframgia** [surveyjs/survey-analytics#314]
For now, the text is cut off.
Which option can we show full title and answer?

![image](https://user-images.githubusercontent.com/23466462/221412769-51629458-4dac-4b91-adf6-e7049c375550.png)

Link demo:

https://surveyjs.io/dashboard/examples/export-survey-results-to-csv-files/reactjs

**Comment by JaneSjs** [comment]
Hello @PhuHoaframgia,
SurveyJS Dashboard uses [a Tabulator library](https://tabulator.info/). If you wish to resize table columns to fit their contents, set a tabulator's `layout` option to [fitDataTable](https://tabulator.info/examples/4.7#fittodatatable). You can access tabulator settings using `options.tabulatorOptions`. Consider this [example](https://plnkr.co/edit/MxdDnwqxu2FXbuOh?preview):
```
var surveyAnalyticsTabulator = new SurveyAnalyticsTabulator.Tabulator(survey, 
      data.Data);
surveyAnalyticsTabulator.options.tabulatorOptions.layout = "fitDataTable";      
```
Please let me know if you have further questions.
