### ISSUE TITLE
Support different calculation types for numeric answers - sum, avg, min, max and so on

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-analytics#34]
See this thread for more details - https://surveyjs.answerdesk.io/ticket/details/t4431/graph-chart-visuals-for-numeric-datatypes

> Suppose we want to get the number of covid patients in each hospital, then this data can be presented in several ways like total number of patients, average number of patients in each hospital, maximum and minimum number of patients across all hospitals. This can help to take decisions. (Furthermore scattering around these points will provide more useful information - not a required feature).

**Comment by rajeevbagla** [comment]
Can you please let me know when can we expect this enhancement?

**Comment by tsv2013** [comment]
We'll update this thread as soon as will have any results.

**Comment by tsv2013** [comment]
Are you talking about the simple text numeric input question type?
