### ISSUE TITLE
Create a demo for `VisualizerFactory`

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-analytics#341]
https://surveyjs.io/dashboard/documentation/api-reference/visualizerfactory

It's unclear how to use this object without a real use-case and a demo.

**Comment by tsv2013** [comment]
It allows to create a visualization component for a single question:
```JS
            const visualizer = new SurveyAnalytics.VisualizerFactory.createVisualizer(
                survey.getAllQuestions()[0],
                dataFromServer,
                { labelTruncateLength: 27 }
            );
 
            visualizer.render("surveyDashboardContainer");
```

Here is the plunker example - https://plnkr.co/edit/mXOnG89JbAVe0IM6
