### ISSUE TITLE
Allow to have custom file name for downloads in tabulator

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-analytics#342]
There is no way to provide a custom file name for download files in tabulator.
Here is [the ticket in SurveyJS Support forum](https://surveyjs.answerdesk.io/ticket/details/T13030).

**Comment by JaneSjs** [comment]
Use the [downloadOptions.fileName](https://github.com/surveyjs/survey-analytics/blob/332cc6012a9acbbce5d0bff42e1d8a1e5a0a45ce/src/tables/tabulator.ts#L34) property to define the name of an exported file for all export types.
```js
var vizPanelOptions = {
  downloadOptions: {
     fileName: "Sample"
   }
};
var surveyAnalyticsTabulator = new SurveyAnalyticsTabulator.Tabulator(survey, data.Data, vizPanelOptions);
```
[Example](https://plnkr.co/edit/8F1soVINcP2SZsSL)
***
For the record: to access an exported file, according to the Tabulator documentation ([Download Callbacks](https://tabulator.info/docs/5.4/callbacks#download)), use the `downloadReady` callback to intercept the download file data before a file is downloaded.

In SurveyJS Dashboard, it is possible to access this callback using the [tabulatorTables](https://github.com/surveyjs/survey-analytics/blob/f2fdde1b292b33b18a5d91675e18672068346e72/src/tables/tabulator.ts#L106) object instance. Note that this object is available after a `render` function of a dashboard is called.
```js{8-14}
var visPanel = new SurveyAnalyticsTabulator.Tabulator(
   survey,
   dataFromServer
);

visPanel.render("surveyDashboardContainer");

visPanel.tabulatorTables.options.downloadReady = function(fileContents, blob){
      //fileContents - the unencoded contents of the file
      //blob - the blob object for the download
      //custom action to send blob to server could be included here
      return blob;
   }
});
```
[Example](https://plnkr.co/edit/OKa6djRzphnqV8Dq).

If you need to perform changes to the table data before it is parsed into the download file, use the [onDownloadCallback](https://github.com/surveyjs/survey-analytics/blob/f2fdde1b292b33b18a5d91675e18672068346e72/src/tables/tabulator.ts#L60) function.
