### ISSUE TITLE
Text in table isn't showing array results

### ISSUE THREAD

**Issue by MaelLyon** [surveyjs/survey-analytics#363]
If value for a question with type 'text' is an array. Wordcloud is working, but not text in table

**Comment by JaneSjs** [comment]
Hello,
The value of a question with `type: "text"` is supposed to be a plain string value. If you wish to set a question value to an array of strings, consider Checkboxes ([View Demo](https://surveyjs.io/form-library/examples/create-checkboxes-question-in-javascript/reactjs)) or a TagBox question ([View Demo](https://surveyjs.io/form-library/examples/how-to-create-multiselect-tag-box/reactjs)).

Alternatively, you can register a custom visualizer for your Text question and visualize an array of values as needed. For more information, please refer to the following demo: [Custom Bar Chart](https://surveyjs.io/dashboard/examples/how-to-plot-survey-data-in-custom-bar-chart/reactjs).

Please let me know if either option can fit your needs.

**Comment by MaelLyon** [comment]
Hello,
At the moment I set up a custom visualizer for it. 
But I thought it was a bug because in the code it seems to be some implementation for array  but not functional ([PR#364](https://github.com/surveyjs/survey-analytics/pull/364))

I want the users to be able to select multiple plain-text answers. I then have an array of strings.

**Comment by tsv2013** [comment]
I've just checked examples from this repo. Wordcloud and text table both work ok for me. Any visualizer accepts an array of survey results (objects with question names as keys) and extracts necessary data from passed array.

Do you need an example?

**Comment by JaneSjs** [comment]
Hello @MaelLyon,
I created the following demo: [View Demo](https://codesandbox.io/s/add-surveyjs-analytics-to-a-react-application-forked-g7fm43?file=/src/App.js).

A Text question receives an array of string values:
```
const surveyResults = [
  {
    q1: ["Orange", "Apple", "Banana", "Mango"]
  }
];
```
Both Wordcloud and Text in Table visualizers can correctly dislay question values:
![image](https://github.com/surveyjs/survey-analytics/assets/22372972/417ac196-f0ed-49ac-865d-b9bf278c81ae)

Please share a problematic demo for research.
