### ISSUE TITLE
Unable to render Data Table in Analytics in Vue

### ISSUE THREAD

**Issue by edisonneo** [surveyjs/survey-analytics#40]
I am unbale to render the data table in my Vue component. I am guessing it is the way that jquery is loaded in the vue app.

I am just loading jquery and the plugins using the script tags in the index.html file 

```
    <script src="https://unpkg.com/jquery"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.js"></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.2/js/dataTables.colReorder.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.4/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.js"></script>
    <script src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.js"></script>
```

while survey-analytics is loaded in the vue component

```
import * as SurveyAnalytics from 'survey-analytics';
```

And the table is created as such:

```
const surveyTableNode = document.getElementById('surveyTable');
surveyTableNode.innerHTML = '';

const surveyAnalyticsDataTables = new SurveyAnalytics.DataTables(surveyTableNode, this.survey, normalizedData);

surveyAnalyticsDataTables.render();
```
However I am getting this error in the .render() function.

<img width="911" alt="Screen Shot 2020-07-07 at 2 59 58 PM" src="https://user-images.githubusercontent.com/13084787/86732063-ab361e00-c062-11ea-9396-e10f360a12dc.png">

and the error occurs at this line in survey.analytics.js

``` var datatableApiRef = (this.datatableApi = jquery__WEBPACK_IMPORTED_MODULE_1__(tableNode).DataTable(options));```

Any idea what could be the problem? And is there a better way to load jquery and the plugins in vue apps?

Any help would be great thanks

**Comment by tsv2013** [comment]
Have you added jQuery (the jQuery itself, not `jquery-ui`) script on your page?

**Comment by edisonneo** [comment]
Yeap sorry I didnt add a new line in the comment. jquery is added at the top

**Comment by edisonneo** [comment]
Forgot to add 
survey-analytics version: "1.7.18"
survey-vue version: "1.7.15"

**Comment by tsv2013** [comment]
Unfortunately this information doesn't help. Could you share a minimal live sample illustrating the issue? You can use the https://stackblitz.com/ or similar sandbox application.

**Comment by edisonneo** [comment]
Alright i'll try to do that

**Comment by edisonneo** [comment]
https://21mwx.csb.app/

Here is the sandbox. I managed to get rid of the webpack imported module error but I am still facing an error of the row being unable to render.

`[Vue warn]: Error in mounted hook (Promise/async): "TypeError: Cannot create property 'Row 1' on string '4'"`


Anyway, I am trying to render the table so that I can export the responses to csv. I am wondering if there is an available method in SurveyJS which I can attach to a button to export the data. So far I have been unable to find anything on the documentation regarding that.

**Comment by edisonneo** [comment]
This is the editor link
https://codesandbox.io/s/agitated-chatterjee-21mwx?file=/public/index.html

**Comment by tsv2013** [comment]
Thank you, I'll take a look

**Comment by tsv2013** [comment]
You're triyng to apply wrong formatted data to "matrixdropdown" question (question3). It should be something like this:
```JS
question3: {"Row 1": {"Column 1": "4"}},
```
instead of simply "4".

But there is another issue - VueJS can't find the `DataTable` constructor. And I'm working right now on this issue.

**Comment by tsv2013** [comment]
I've fixed the "DataTable" is not a function issue via the above commit and added datatables demo page to the https://github.com/surveyjs/surveyjs_vue_quickstart repo via the https://github.com/surveyjs/surveyjs_vue_quickstart/commit/88e604f4ea97b3a2dd2e59620e34a686a88fcafb commit.

The fix will be available in the nearest update

**Comment by yeweiwei-xin** [comment]
@tsv2013 the surveyjs_vue_quickstart  repo still said 
vue.esm.js?6f63:1897 TypeError: __WEBPACK_IMPORTED_MODULE_1_survey_analytics__.DataTables is not a constructor
Any idea what could be the problem? 
Any help would be great thanks
