### ISSUE TITLE
Incorrect process checkbox question data

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-analytics#400]
Here is [the example](https://plnkr.co/edit/Xnf6SyhBIamxf56F). All bars should be equal, since the question value for the checkbox has select all for survey responses.

**Comment by tsv2013** [comment]
I've checked your example and found out that you are visualizing a "ranking" question type.
A "ranking" question type is shown by dedicated "RankingPlotly" visualizer. It computes item weight taking in account the position of the item in answer array. This was done to illustrate what item was rated as more valuable.

If you want a "ranking" to be visualized as an ordinary "checkbox" you can override it visualizer definition:
```JS
    SurveyAnalytics.VisualizationManager.unregisterVisualizer(undefined, SurveyAnalytics.RankingPlotly);
    SurveyAnalytics.VisualizationManager.registerVisualizer("ranking", SurveyAnalytics.SelectBasePlotly);
```
Here is the updated plunker link - https://plnkr.co/edit/vYoUYFbFbDWZFltZ

I've updated the original thread is SC
