### ISSUE TITLE
Tabulator - Add dropdown select as column filter

### ISSUE THREAD

**Issue by DevNull-00** [surveyjs/survey-analytics#439]
Right now the tabulator component only allows for simple search filtering.
It would be very cool if, for question that have multiple choices like checkboxes and radio groups, the filter field could dynamically adapt and change in a dropdown that automatically looks up possible values and populates the choices. (See Tabulator example: https://tabulator.info/examples/6.2?#filter-header)

Thank you!

**Comment by JaneSjs** [comment]
Hi @DevNull-00,
You can customize the Tabulator to display header filters. For more information, please visit [this support thread](https://surveyjs.answerdesk.io/internal/ticket/details/T15561).

Let me know if you require further assistance.

**Comment by DevNull-00** [comment]
@JaneSjs Thank you that was very helpful!
The only other issue I'm having is that for some reason I can't change the Tabulator locale.

I instantiate the component the following way: (Angular)
```js
const options = {
  tabulatorOptions: {
    downloadRowRange: 'active',
  },
  downloadOptions: {
    fileName: 'UserFilter'
  },
  downloadButtons: []
}
TableExtensions.unregisterExtension('column', 'filter');
this.table = new Tabulator(this.surveyModel, this.surveyAnswers, options);
this.table.locale = 'it'; // setting language to italian
this.table.render(this.surveyTable.nativeElement);
this.table.tabulatorTables.options.downloadReady = this.downloadReady.bind(this);
```

But for some reason the table language (paginator, search filters and other table elements) is still in English. Am I missing something?
