### ISSUE TITLE
Download buttons broken with remote pagination

### ISSUE THREAD

**Issue by TwilightCoder** [surveyjs/survey-analytics#445]
This is a follow-up to #329

When enabling server-side pagination by passing a function for data instead of array, all the download buttons (pdf, excel, CSV) fail silently with the following console error:

<img width="638" alt="download-error" src="https://github.com/surveyjs/survey-analytics/assets/16983017/c04cdb70-b392-416a-94c6-a62b7b120834">

I tried to debug it in the browser, but the browser doesn't seem to load the right context (for `this`) here.

**Comment by tsv2013** [comment]
Built-in download buttons weren't supposed to work with server-side pagination.

You can check the corresponding issue in the tabulator repo -
https://github.com/olifolkerd/tabulator/issues/3154#issuecomment-757481722

> This isnt a bug.
> 
> This is a physical limitation of the remote pagination methodology,
> 
> The table only stores the current page in memory, the rest is on the server, so there is no way to create a download from all the data because it simple is not there.
> 
> Remote pagination is specifically designed to only pull down the needed data, if a table has 10,000 pages for example then it could take many minutes to pull all that data down before the table was ready to be downloaded.
> 
> If you wish to download in this fashion you should either generate the doc on the server and transfer it, or pull all the data down to the client and then load it into the table for generation

**Comment by TwilightCoder** [comment]
Thanks for linking that ticket. I get the "physical limitation" mentioned around exporting the remote data, but the export is still functional in that ticket for the data loaded in memory. The ticket author there is just complaining that `the downloaded data should contain all rows and not the current page rows only.` 

Whereas, in the surveyJS table, the export does not work at all and errors out due to some context issue with `this.data` being undefined in the following line as shown above:
https://github.com/surveyjs/survey-analytics/blob/4997d6a91ddd67e842f62024408e13ccbcbda26c/src/tables/tabulator.ts#L266
Being able to export, say, a 100 rows at a time still looks useful than no inbuilt export behavior at all.

**Comment by tsv2013** [comment]
Thank you for clarification!
I've fixed the issue via the above commit.
