### ISSUE TITLE
The `hideEmptyAnswers: true` doesn't hide empty charts

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#480]
T20075 - how to send filtered form json in analytics
https://surveyjs.answerdesk.io/internal/ticket/details/T20075
***
[View Demo](https://plnkr.co/edit/Dp3BXFnzO2JsvRHb)

![image](https://github.com/user-attachments/assets/8d56d326-d358-4c8d-9ad0-bf00242fd3a1)

**Comment by tsv2013** [comment]
This option was designed to hide unused choices in select question types (radiogroup, checkbox, dropdown and so on). It hides empty bars in a diagram only.
