### ISSUE TITLE
Multiple Textboxes - A Text in Tables visualizer doesn't display field titles/column headers

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#483]
T20329 - Multiple Textboxes question is not visualized
https://surveyjs.answerdesk.io/internal/ticket/details/T20329
***
[View Demo](https://plnkr.co/edit/RdJOJWcTRIuQiSlP)
A Text in Tables visualizer doesn't display field titles/column headers.
![image](https://github.com/user-attachments/assets/f38618a7-056e-489a-9f60-90e28114458f)

**Comment by tsv2013** [comment]
Implemented via referenced commit
