### ISSUE TITLE
The setColumnWidth function doesn't decrease a column width

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#486]
T20497 -  Reduce the column width
https://surveyjs.answerdesk.io/internal/ticket/details/T20497

https://github.com/surveyjs/survey-analytics/blob/d51e32a1344174b59d5e86fc449c54fbafde6c56/src/tables/tabulator.ts#L383C10-L383C24

[View Demo](https://plnkr.co/edit/qFJOuKwJcSCmO04O)

**Comment by tsv2013** [comment]
Here is the temporary workaround - https://plnkr.co/edit/klkD4g5pj7vh2vH5
