### ISSUE TITLE
I get "Cannot read property 'extend' of undefined" when I try to instantiate a DataTables object.

### ISSUE THREAD

**Issue by radoeska-v** [surveyjs/survey-analytics#49]
When I run the code, I noticed that the `window["jquery"]` is _undefined_.

I am using Angular 9 and I installed the `survey-analytics` npm package.

In the component I imported:
```
import { SurveyModel } from 'survey-core';
import * as SurveyAnalytics from 'survey-analytics';
```

And I am trying to create a `DataTables` for the Feedback Survey example:
```
const surveyAnalyticsDataTables = new SurveyAnalytics.DataTables(
        document.getElementById('surveyAnalyticsDomNode'),
        new SurveyModel(feedbackSurveyJSON),
        normalizedData,
        dataTablesOptions
      );

surveyAnalyticsDataTables.render();
```

There is no documentation for the `DataTablesOptions` but they are required in the `DataTables` _ctor_, so I set the default values:
```
const dataTablesOptions = {
        buttons: true,
        dom: '',
        orderFixed: [],
        rowGroup: false,
        headerCallback: () => {},
      };
```

**Comment by tsv2013** [comment]
In Angular applications all 3rd party scripts (especially non-modular like datatables.js) can be loaded in the https://github.com/surveyjs/surveyjs_angular_cli/blob/master/angular.json#L46-L57 file, scripts section.

Survey-analytics package is in active development right now and has many undocumented code. As for options object - 
options object can be ommited.

**Comment by radoeska-v** [comment]
Hey, the problem was in the `DataTablesOptions`. I just passed an `undefined` for the `options` parameter in the `DataTables` _ctor_ and the table has rendered as expected and without errors.

`DataTablesOptions` cannot be omitted, a see that it is required here: https://github.com/surveyjs/survey-analytics/blob/7f7e6e07fd597bef411c9b41052cd1fcf8b3f033/src/tables/datatables.ts#L55  There's no default value provided. And my code does not compile without the `options` parameter.
