### ISSUE TITLE
ERROR TypeError: d.autoTable is not a function

### ISSUE THREAD

**Issue by 4mit** [surveyjs/survey-analytics#81]
i have below in my index.html 

- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
-     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.10/jspdf.plugin.autotable.min.js"></script>
-     <script type="text/javascript" src="https://oss.sheetjs.com/sheetjs/xlsx.full.min.js"></script>
-     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js"></script>
-     <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/css/tabulator.min.css"/>
-     <link href="https://surveyjs.azureedge.net/1.7.25/survey.analytics.tabulator.css" rel="stylesheet"/>
-     <script src="https://surveyjs.azureedge.net/1.7.25/survey.analytics.tabulator.js"></script>

![image](https://user-images.githubusercontent.com/19636777/89920032-97f60f80-dc19-11ea-8efa-85fb7690b0d7.png)
export pdf is throwing error:
ERROR TypeError: d.autoTable is not a function

**Comment by dk981234** [comment]
Hello,

Please check this [example](https://surveyjs.io/Examples/Analytics?id=nps-tabulator&platform=jQuery&theme=modern#content-result). 
Did you include https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js?

Thanks,
Dmitry
SurveyJS Team

**Comment by 4mit** [comment]
![image](https://user-images.githubusercontent.com/19636777/90335809-0ad60080-dff5-11ea-967a-efb328597654.png)
yes , my index.html looks like this

**Comment by tsv2013** [comment]
Does the sample mentioned above (https://surveyjs.io/Examples/Analytics?id=nps-tabulator&platform=jQuery&theme=modern#content-result) work fr you?

**Comment by 4mit** [comment]
yes. but when i'm trying to add it to my app it not working ? wondering how . not sure about the reason

**Comment by tsv2013** [comment]
If you provide us with a minimal live reproducible sample (https://stackoverflow.com/help/minimal-reproducible-example), we could take a look.
