### ISSUE TITLE
error TS2307: Cannot find module 'plotly.js'.

### ISSUE THREAD

**Issue by radoeska-v** [surveyjs/survey-analytics#84]
Hello,

I am using the surveyJS in my Angular 9 App and today I updated to v1.7.26.

But my app does not compile and throws this error:
```
ERROR in node_modules/survey-analytics/survey.analytics.d.ts:692:33 - error TS2307: Cannot find module 'plotly.js'.

692     get chart(): Promise<import("plotly.js").PlotlyHTMLElement>;
                                    ~~~~~~~~~~~
node_modules/survey-analytics/survey.analytics.d.ts:709:33 - error TS2307: Cannot find module 'plotly.js'.

709     get chart(): Promise<import("plotly.js").PlotlyHTMLElement>;
```

I fixed it locally by replacing `plotly.js` with `plotly.js-dist` on both lines (692 & 706) but I am not sure if this is an appropriate solution.

**Comment by tsv2013** [comment]
Can you provide us with the sample illustrating the issue? Probably this repo can be used as a starting point - https://github.com/surveyjs/surveyjs_angular_cli

**Comment by radoeska-v** [comment]
While preparing the sample I solved the problem with:
```
npm install plotly.js
```
